/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CAL_H_RPCGEN
#define _CAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct add_1_argument {
	int first;
	int second;
};
typedef struct add_1_argument add_1_argument;

struct sub_1_argument {
	int first;
	int second;
};
typedef struct sub_1_argument sub_1_argument;

struct mul_1_argument {
	int first;
	int second;
};
typedef struct mul_1_argument mul_1_argument;

struct div_1_argument {
	int first;
	int second;
};
typedef struct div_1_argument div_1_argument;

struct pow_1_argument {
	int first;
	int second;
};
typedef struct pow_1_argument pow_1_argument;

#define CALEPROG 0x20000001
#define CALMESSAGEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(int , int , CLIENT *);
extern  int * add_1_svc(int , int , struct svc_req *);
#define SUB 2
extern  int * sub_1(int , int , CLIENT *);
extern  int * sub_1_svc(int , int , struct svc_req *);
#define MUL 3
extern  int * mul_1(int , int , CLIENT *);
extern  int * mul_1_svc(int , int , struct svc_req *);
#define DIV 4
extern  int * div_1(int , int , CLIENT *);
extern  int * div_1_svc(int , int , struct svc_req *);
#define POW 5
extern  int * pow_1(int , int , CLIENT *);
extern  int * pow_1_svc(int , int , struct svc_req *);
extern int caleprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
#define SUB 2
extern  int * sub_1();
extern  int * sub_1_svc();
#define MUL 3
extern  int * mul_1();
extern  int * mul_1_svc();
#define DIV 4
extern  int * div_1();
extern  int * div_1_svc();
#define POW 5
extern  int * pow_1();
extern  int * pow_1_svc();
extern int caleprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_add_1_argument (XDR *, add_1_argument*);
extern  bool_t xdr_sub_1_argument (XDR *, sub_1_argument*);
extern  bool_t xdr_mul_1_argument (XDR *, mul_1_argument*);
extern  bool_t xdr_div_1_argument (XDR *, div_1_argument*);
extern  bool_t xdr_pow_1_argument (XDR *, pow_1_argument*);

#else /* K&R C */
extern bool_t xdr_add_1_argument ();
extern bool_t xdr_sub_1_argument ();
extern bool_t xdr_mul_1_argument ();
extern bool_t xdr_div_1_argument ();
extern bool_t xdr_pow_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CAL_H_RPCGEN */
