/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cal.h"

bool_t
xdr_add_1_argument (XDR *xdrs, add_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->first))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->second))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sub_1_argument (XDR *xdrs, sub_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->first))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->second))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mul_1_argument (XDR *xdrs, mul_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->first))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->second))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_div_1_argument (XDR *xdrs, div_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->first))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->second))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pow_1_argument (XDR *xdrs, pow_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->first))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->second))
		 return FALSE;
	return TRUE;
}
