/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cal.h"


void
caleprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int add_1_first = 4;
	int add_1_second = 5;
	int  *result_2;
	int sub_1_first;
	int sub_1_second;
	int  *result_3;
	int mul_1_first;
	int mul_1_second;
	int  *result_4;
	int div_1_first = 4;
	int div_1_second = 4;
	int  *result_5;
	int pow_1_first;
	int pow_1_second;

#ifndef	DEBUG
	clnt = clnt_create (host, CALEPROG, CALMESSAGEVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	add_1(0, 0, clnt);
	result_1 = add_1(add_1_first, add_1_second, clnt);
	fprintf(stdout, "%d\n", *result_1);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = sub_1(sub_1_first, sub_1_second, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = mul_1(mul_1_first, mul_1_second, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = div_1(div_1_first, div_1_second, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = pow_1(pow_1_first, pow_1_second, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	caleprog_1 (host);
	
	CLIENT *clnt;
	clnt = clnt_create (host, CALEPROG, CALMESSAGEVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}


exit (0);
}
