/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cal.h"

int *
add_1_svc(int first, int second,  struct svc_req *rqstp)
{
	static int  result;
	result = first + second;
	return &result;
}

int *
sub_1_svc(int first, int second,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = first - second;
	return &result;
}

int *
mul_1_svc(int first, int second,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = first * second;
	return &result;
}

int *
div_1_svc(int first, int second,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = first / second;
	return &result;
}

int *
pow_1_svc(int first, int second,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int cnt = 0;
	result = 1;

	while(cnt < second){
		result *= first;
		cnt+=1;
	}

	return &result;
}
